[package]
name = "csvlens"
version = "0.1.4"
authors = ["Yung Siang Liau <liauys@gmail.com>"]
license = "MIT"
description = "Command line csv viewer"
readme = "README.md"
homepage = "http://github.com/YS-L/csvlens"
repository = "http://github.com/YS-L/csvlens"
exclude = [".github/*", "tests/*"]
keywords = ["cli"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
tui = "0.15"
termion = "1.5"
anyhow = "1.0"
clap = { version = "3.1.0", features = ["derive"] }
tempfile = "3.3.0"