[package]
name = "csvlens"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
tui = "0.15"
termion = "1.5"
anyhow = "1.0"
clap = { version = "3.1.0", features = ["derive"] }
